---
title: Perle di Nerdezza
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Quello che cercavi... Forse.
tagline: Guide, Hack & Cheats, How-To, DIY e pensieri vari.
baseurl:
sass:
  sass_dir: _sass
url: http://rerosku.github.io
navigation:
- text: Home
  url: "/"
- text: About
  url: "/about/"
- text: Archives
  url: "/tags/"
disqus: perledinerdezza
author_name: Rerosku
author_bio: 'Geek, Drogato di Serie TV, Party Animal e fermo sostenitore della scuola
  di pensiero: Massimo Risultato, Minimo Sforzo'
author_url: http://rerosku.github.io
author_location: Biella, Italia
author_image: images/rerosku.jpg
banner_url: http://ororo.tv/ref/382304
banner_image: images/ororo.jpg
twitter_username: perledinerdezza
facebook_username: perle.di.nerdezza
googleplus_username: "+AlessandroNardi"
github_username: rerosku
instagram_username: perle.di.nerdezza
paginate: 5
paginate_path: "/blog/page:num/"
gems:
- jekyll-paginate
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false
