title: "Alessandro Nardi"
description: "Reiki, Coaching Olistico e Consapevolezza di Sé"
url: "https://www.rerosku.it/" # lascia vuoto per sviluppo locale
baseurl: "rerosku.github.io" # o il nome del repo se su GitHub Pages

# Tema
theme: null # questo è il tema stesso

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: "pages"
    values:
      layout: page

# Permalink
permalink: /blog/:year/:month/:day/:title/

# Categories
categories:
  - benessere
  - reiki
  - consapevolezza
  - crescita

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
