# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Perle di Nerdezza"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Quello che cercavi...  Forse. "

# Tagline near the site title
tagline: "Guide, Chat, How-to, DIY e pensieri vari."

# The subpath of your site, e.g. /blog, for generating urls
baseurl: /

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://rerosku.GitHub.io"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
# - text: Style Guides
#   url: /style-guide/
- text: Archivio
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: "perledinerdezza"

# Author information - author info at the bottom of the post
author_name: "Rerosku"
author_bio: "Geek, drogato di serie Tv,  party Animal e fermo sostenitore della teoria:  "Massimo Risultato,  Minimo Sforzo"
author_url:  "http://rerosku.GitHub.io"
author_location: "Biella, Italia"
author_image: https://tlgur.com/d/yGOVznM8

# Sidebar Add banner
# banner_url: "http://justgoodthemes.com"
# banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
# mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "nardialex"
facebook_username: "nekonata.liberaj"
# googleplus_username: "+rerosku"
github_username: "rerosku"
codepen_username: "#"
# dribbble_uername: "#"
medium_username: "@username"
instagram_username: "rerosku"
# pinterest_username: "username"
linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false
